### ISSUE TITLE
Add Vivaldi browser detection?

### ISSUE THREAD

**Issue by Verulam** [mckamey/cssuseragent#4]
Although only used by a minority, support for the new Vivaldi browser might be worth adding. As far as I can make out, it's Google Chrome-based and the user-agent string seems very similar to that for Chrome, e.g.:
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.89 Vivaldi/1.0.94.2 Safari/537.36

**Comment by mckamey** [comment]
Done. I wonder why they bothered to make this browser.
