### ISSUE TITLE
NPM compatibility

### ISSUE THREAD

**Issue by jperasmus** [mckamey/cssuseragent#6]
Hi,

Would you please be so kind as to publish this package to NPM as well?

It should be as simple as adding a `package.json` file and then running `npm publish` if you have an npm account.

https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by sota1235** [comment]
It's good idea!!

Please check the Pull Request( #5 )!! @mckamey

**Comment by jarektomanek** [comment]
Looking forward for publishing it in NPM!

**Comment by mckamey** [comment]
Should be good to go: https://www.npmjs.com/package/cssuseragent
